name: projetdeploifront
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - streamlit==1.42.0
  - httpx==0.28.1
  - pydantic==2.10.6
  - requests==2.32.3
  - ruff==0.9.6
  - isort==5.10.1
  - pre-commit==4.1.0
