repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.278  # Remplace par la dernière version de Ruff
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Essaie avec une version plus ancienne
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
