version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      # the port 11434 might already be in use on your laptop, change it for 11435
      - 11435:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    pull_policy: always
    tty: true
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    networks:
      - backend-ollama

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_SERVICE_NAME=ollama:11434
    networks:
      - backend-frontend
      - backend-ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - backend-frontend

networks:
  backend-ollama:
  backend-frontend: