version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Assurez-vous que c'est le bon Dockerfile
    image: projettest-frontend:latest  # Nom de l'image à utiliser
    ports:
      - "8501:8501"
    #depends_on:
    #  - backend

  # Uncomment if you want to add a backend service
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "5000:5000"
