version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    #depends_on:
    #  - backend

  #backend:
  #  build:
  #    context: ./backend
  #  ports:
  #    - "5000:5000"
