version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Répertoire où se trouve le Dockerfile du backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "5000:5000"  # Port utilisé par FastAPI
    command: uvicorn main:app --host 0.0.0.0 --port 5000

  frontend:
    build:
      context: ./frontend  # Répertoire où se trouve le Dockerfile du frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8501:8501"  # Port utilisé par Streamlit
